export enum AuthPolicy {
  ACCESS_AGENT_AREA = 'ACCESS_AGENT_AREA',
  ACCESS_ADMIN_AREA = 'ACCESS_ADMIN_AREA',
  MANAGE_ASSETS = 'MANAGE_ASSETS',
  MANAGE_KNOWLEDGE_BASE = 'MANAGE_KNOWLEDGE_BASE',
  MANAGE_REFERENTIALS = 'MANAGE_REFERENTIALS',
  VALIDATE_KNOWLEDGE_BASE = 'VALIDATE_KNOWLEDGE_BASE',
}
