export enum NotificationType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_COMMENTED = 'TICKET_COMMENTED',
  TICKET_STATUS_CHANGED = 'TICKET_STATUS_CHANGED',
}
