export type TicketSummarySnapshot = {
  assignedToUserId: string | null;
  assignmentGroupId: string | null;
  archivedAt: string | null;
  categoryId: string;
  channelId: string | null;
  ciId: string | null;
  createdAt: string;
  createdByUserId: string;
  id: string;
  number: string;
  priorityId: string;
  priorityName: string | null;
  requestedForUserId: string | null;
  resolutionDueAt: string | null;
  resolutionSlaStatus: string | null;
  responseDueAt: string | null;
  responseSlaStatus: string | null;
  slaPausedAt?: string | null;
  slaPausedDurationMs?: number;
  status: string;
  title: string;
  type: string;
};
