export const SUPPORT_GROUP_REPOSITORY = Symbol('SUPPORT_GROUP_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const SERVICE_REPOSITORY = Symbol('SERVICE_REPOSITORY');
export const CHANNEL_REPOSITORY = Symbol('CHANNEL_REPOSITORY');
export const PRIORITY_REPOSITORY = Symbol('PRIORITY_REPOSITORY');
